### ISSUE TITLE
Still needed in 1.1.0

### ISSUE THREAD

**Issue by w-bruns** [flatsurf/e-antic#230]
The Normaliz installation script for e-aqntic contains the lines

```
sed -i -e s/fmpq_poly_add_fmpq/fmpq_poly_add_fmpq_eantic/g upstream/patched/fmpq_poly_add_fmpq.c
sed -i -e s/fmpq_poly_add_fmpq/fmpq_poly_add_fmpq_eantic/g upstream/patched/nf_elem_add_fmpq.c
```

Are they still needed in 1.1.0?

**Comment by saraedum** [comment]
If you want to build statically, this is still needed I think. Otherwise, it's not needed.

Otherwise, these don't depend on the version of e-antic but on the version of its dependencies, namely that patch is not needed if FLINT is at least 2.8.4 (the latest release) but there is no flag to disable the patch in that case yet.
